#' PPI generated by the Ascher Lab at the Baker Institute
#'
#' A PPI made from combining multiple online interaction networks to make a meta-graph of public interaction data.
#' Edges are supported by a range of different evidence types
#'
#' @format An igraph object with 15756 vertices and 174414 edges:
#'
#' @source \email{david.ascher@unimelb.edu.au} for details
"ascher_graph"


#' Human reference interactome version 3.0
#'
#' A PPI developed from large scale chemical genetic yeast 2 hybrid screening.
#' All interactions were validated in at least two screens.
#'
#' @format An igraph object with 8010 vertices and 50568 edges
#'
#' @source \url{http://interactome.baderlab.org/} for further details details
"huri_graph"

#' The STRING PPI
#'
#' This PPI is based on experimentally validated interactions withiin the STRING database.
#' Only interactions with a score > 400 (high-confidence) are included.
#'
#' @format An igraph object with 12089 vertices and 86383 edges
#'
#' @source \url{https://string-db.org/} for details
"STRING_graph"

#' drug potential scores
#'
#' @format A dataframe with 15781 rows and two columns:
#' \describe{
#'   \item{name}{uniprotswissprot}
#'   \item{druggability}{Fpocket drug score (0,1)}
#' }

"drug_score"
