#' PPI generated by the Ascher Lab at the Baker Institute
#'
#' A PPI: give some details about what the interactions represent here.
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{price}{price, in US dollars}
#'   \item{carat}{weight of the diamond, in carats}
#'   ...
#' }
#' @source \email{david.ascher@unimelb.edu.au} for details
"ascher_graph"


#' Human reference interactome version 3.0
#'
#' A PPI developed from large scale chemical genetic yeast 2 hybrid screening.
#' All interactions were validated in at least two screens.
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{price}{price, in US dollars}
#'   \item{carat}{weight of the diamond, in carats}
#'   ...
#' }
#' @source \url{http://interactome.baderlab.org/} for further details details
"huri_graph"

#' The STRING PPI
#'
#' This PPI is based on experimentally validated interactions withiin the STRING database.
#' Only interactions with a score > 400 (high-confidence) are included
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{price}{price, in US dollars}
#'   \item{carat}{weight of the diamond, in carats}
#'   ...
#' }
#' @source \url{https://string-db.org/} for details
"STRING_graph"

#' drug potential scores
#'
#' @format
#' \describe{
#'   \item{name}{uniprotswissprot}
#'   \item{druggability}{Fpocket}
#' }

"drug_score"
